default:
	gcc -Wall myfind.c -o myfind.out

1:
	./myfind.out /home/kuldip/Desktop/OS_Lab

2:
	./myfind.out /home/kuldip/Desktop -mmin +1 -mday -6

3:
	./myfind.out -perm 0775

4:
	./myfind.out /home/kuldip/Desktop -name *.pdf

5:
	./myfind.out /home/kuldip/Desktop -name p*b

6:
	cd ../..
	OS_Lab/Lab08/myfind.out -name *.py
#Run the last line of command by typing in terminal                          